name: Node.js CD - Production

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: appleboy/ssh-action@master
              name: Deploy production on VPS
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                passphrase: ${{ secrets.SERVER_PASSPHRASE }}
                port: 22
                script: |
                    export PATH="$PATH:/home/reginald/.nvm/versions/node/v20.9.0/bin/"
                    export NVM_DIR=~/.nvm
                    source ~/.nvm/nvm.sh
                    nvm use --lts
                    cd ~/dev/repos/beequiz/beequiz-app
                    git checkout main
                    git fetch --all
                    git reset --hard origin/main
                    yarn install
                    yarn build --configuration production
                    pm2 delete beequiz-app
                    pm2 start dist/beequiz-app/server/server.mjs --namespace beequiz --name beequiz-app
